// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClngnGYFiNe1nyh3Xd3opX4rn4gmvbk_0',
    appId: '1:82486531307:web:faee9e89684f3ed0685aae',
    messagingSenderId: '82486531307',
    projectId: 'chatapp-3d75a',
    authDomain: 'chatapp-3d75a.firebaseapp.com',
    storageBucket: 'chatapp-3d75a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiEF9S-LneX-YKa-mcXSx9qNy9pzbF5nA',
    appId: '1:82486531307:android:300272b6fdc23d9e685aae',
    messagingSenderId: '82486531307',
    projectId: 'chatapp-3d75a',
    storageBucket: 'chatapp-3d75a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8-oNnWxk1xgTfw7RhpAp1E_n2yTO33yc',
    appId: '1:82486531307:ios:a6c37f5deb5cb2ac685aae',
    messagingSenderId: '82486531307',
    projectId: 'chatapp-3d75a',
    storageBucket: 'chatapp-3d75a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
